PYTHON ?= python3
PYTHONPATH := backend

.PHONY: test test-bd

test:
	LOCAL_SCRAPER_SKIP_HEALTHCHECK=1 PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pytest -q

test-bd:
	LOCAL_SCRAPER_SKIP_HEALTHCHECK=1 PYTHONPATH=$(PYTHONPATH) $(PYTHON) -m pytest -q -k bd_
