"""Initial schema

Revision ID: 15afad0d971b
Revises: 
Create Date: 2025-11-09 11:45:28.504549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15afad0d971b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allegro_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(), nullable=False),
    sa.Column('lowest_price', sa.Float(), nullable=True),
    sa.Column('sold_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('not_found', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allegro_cache_ean'), 'allegro_cache', ['ean'], unique=True)
    op.create_index(op.f('ix_allegro_cache_id'), 'allegro_cache', ['id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_id'), 'import_jobs', ['id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_id'), 'exports', ['id'], unique=False)
    op.create_table('product_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('normalized_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_inputs_ean'), 'product_inputs', ['ean'], unique=False)
    op.create_index(op.f('ix_product_inputs_id'), 'product_inputs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_inputs_id'), table_name='product_inputs')
    op.drop_index(op.f('ix_product_inputs_ean'), table_name='product_inputs')
    op.drop_table('product_inputs')
    op.drop_index(op.f('ix_exports_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_import_jobs_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_allegro_cache_id'), table_name='allegro_cache')
    op.drop_index(op.f('ix_allegro_cache_ean'), table_name='allegro_cache')
    op.drop_table('allegro_cache')
    # ### end Alembic commands ###
